// Generated by CoffeeScript 1.6.3
(function() {
  window.onload = function() {
    var editor;
    editor = new ICE.IceEditor(document.getElementById('editor'), coffee, coffee_blockify);
    $("#toggle").click(function() {
      return editor.toggle();
    });
    $("#run").click(function() {
      var frame;
      frames[0].location.reload();
      return frame = $("iframe").load(function() {
        frames[0].CoffeeScript["eval"](editor.getValue());
        return frame.unbind("load");
      });
    });
    editor.setValue("distance = (a,b) ->\n  d = 0\n  for char, i in a\n    if char isnt b[i]\n      d += 1\n  return d\nwrite('Guess the 5-letter secret in 20 guesses!')\nsecret = ''\nfor i in [1..5]\n  secret += random('abcdefghijklmnopqrstuvwxyz'.split(''))\nfor i in [1..20]\n  await(read(defer(guess)))\n  if guess is secret\n    write('You got it!')\n    break\n  else\n    write('Nope! You are ' + distance(guess,secret) + ' letters off.')\nwrite('The secret was: ' + secret)");
    return window.editor = editor;
  };

}).call(this);

/*
//@ sourceMappingURL=example.map
*/
